networks:
  toubeelib.net:
    driver: bridge

services:

  # service api.toubeelib : api pour la prise de rdv
  #
  api.toubeelib:
  #  image: 'canals/php:8.3-cli'
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  # service api.praticien.toubeelib : micro-service pour la gestion des praticiens
  api.praticien.toubeelib:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    ports:
      - '6081:80'
    volumes:
      - ./app/praticien:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  # service api.rdv.toubeelib : micro-service pour la gestion des rdv
  api.rdv.toubeelib:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    ports:
      - '6082:80'
    volumes:
      - ./app/rdv:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

    # service api.auth.toubeelib : micro-service pour la gestion des utilisateurs
  api.auth.toubeelib:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    ports:
      - '6083:80'
    volumes:
      - ./app/auth:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

    # service toubeelib.db : base de données postgresql
  toubeelib.db:
    image: 'postgres:latest'
    env_file: ./toubeelibdb.env
    ports:
      - '5432:5432'
    networks:
      - toubeelib.net
    volumes:
      - ./app/sql:/var/sql'
  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - toubeelib.net

  # service guzzle : separation des services
  gateway.toubeelib:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    ports:
      - '6080:80'
    volumes:
      - ./gateway:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public